---
- hosts: localhost
  tasks:
    - block:
        - import_role: name=emit-job-header
        # This depends-on https://review.openstack.org/578234
        - import_role: name=log-inventory
      vars:
        zuul_log_url: "https://ansible.softwarefactory-project.io/logs"

- hosts: all
  pre_tasks:
    - name: Clean workspace
      file:
        path: "{{ ansible_user_dir }}/src"
        state: absent
      become: yes
  roles:
    - prepare-workspace
    - role: validate-host
